name: GameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare WordPress Zip
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $WP_LINK

      - name: Prepare plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes

      - name: Copy Zips to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}   # если есть
          source: "./wordpress.zip, ./wpcontent.zip"
          target: ${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}

      - name: Enable Maintenance Mode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: ".maintenance"
          target: ${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}

      # Распаковка Wordpress
      - name: Update WordPress Core
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            find "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}" -type f -name "*.php" ! -name "wp-config.php" -delete
            rm -r "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wp-admin/" "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wp-includes/"
            unzip -o "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wordpress.zip" -d "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/"
            mv "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wordpress"/* "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/"
            rm -r "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wordpress"

      - name: Update Plugins and Theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            rm -rf "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wp-content/plugins" "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wp-content/mu-plugins" "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wp-content/themes"
            unzip -o "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wpcontent.zip" -d "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wp-content/"

      # Удалить Maintenance Mode и Remove zips
      - name: Disable Maintenance Mode and Remove zips
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            rm -f "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/.maintenance"
            rm -f "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wpcontent.zip"
            rm -f "${{ github.event_name == 'push' && 'public_html' || 'public_html/live' }}/wordpress.zip"
